// External fortune list
const messages = [
            "Candy is delicious.",
            "Don't set zombies on fire.",
            "Don't spit into the wind.",
            "Fear not the ones who snarl. They know nothing. Instead fear the ones who smile. They know something you don't. – Csllia'nahe'artic",
            "'Inconceivable!'<br>If you don't know what this is from, I pity you. – Shirley",
            "Johnnie was a chemist.<br>A chemist he is no more.<br>For what he thought was H₂O<br>Was H₂SO₄.",
            "'Envy eats nothing but its own heart.'<br>– German Proverb",
            "Join the Army!<br>Travel to exotic distant lands!<br>Meet exciting, unusual people;<br>and kill them!",
            "Every time someone says something is impossible, the universe laughs.<br>Eventually someone else proves them <b>wrong</b>.",
            "'True friends stab you in the front.'<br>– Oscar Wilde",
            "Journalists do not live by words alone,<br>although sometimes they have to eat them. – Adlai E. Stevenson",
            "Reality is for people who lack imagination.",
            "'There’s a fine line between genius and insanity. I have erased this line.' – Oscar Levant",
            "Trust, but verify.",
            "'Forgive your enemies, but never forget their names.' -John F. Kennedy",
            "Never moon a werewolf.",
            "'Never try to teach a pig to sing. It wastes your time and annoys the pig.'-Robert A. Heinlein",
            "'The communication of the dead is tongued with fire<br>beyond the language of the living.'<br>– T.S. Eliot, *Little Gidding*",
            "If you have any quote or fortune suggestions,<br>please include credit. Looking them up is a pain. Thanks!",
            "Alright, who murderized Mr. English Language?<br>Oh no! Mr. Common Sense is dead too?!<br>Wait—Bob, what are you doing with that knife? Bob? BOB?",
            "Who stole my candy?!",
            "Error",
            "Help! I'm being held hostage in a fortune cookie factory!",
            "Some people are only alive because it's illegal to shoot them.",
            "You're just jealous because the voices only talk to ME.",
            "'Always remember you're unique—just like everyone else.'-Margaret Mead ",
            "It's bad luck to be superstitious.",
            "'Legend: a lie that has attained the dignity of age.'<br>– H. L. Mencken",
            "When in doubt, be vague.",
            "'Imagination is more important than knowledge. Knowledge is limited; imagination encircles the world.'<br>– Albert Einstein",
            "*Insert message here*<br>*Or here*<br>*No, how about here?*",
            "'We really don't have enemies. It's just that some of our best friends are trying to kill us.'<br>– Lord Palmerston",
            "'The dumber people think you are, the more surprised they'll be when you kill them.'<br>– William Clayton",
            "'Insanity is doing the same thing over and over again but expecting different results.' <br> – Rita Mae Brown in her 1983 novel 'Sudden Death'",
            "'Structure your question so that the answer “No” gets you what you want.'<br>– Lorren 'Rus' Stiles",
            "'When life gives you lemons, make grape juice and watch the world ask how you did it.'<br>– Tori Truax",
            "'Annoyed? It takes 42 muscles to frown, but only 4 to smack them upside the head.' – Unknown",
            "'I have seen the truth… and it makes absolutely no sense.' – Garrison Keillor",
            "'Not one shred of evidence supports the notion that life is serious.' – Friedrich Nietzsche",
            "I didn't do it. Nobody saw me do it. You can't prove anything!",
            "Maybe your eyes are playing tricks on me!",
            "I used to be indecisive... but now I'm not sure.",
            "It's been lovely, but I have to scream now.",
            "'Sanity is a madness put to good uses.' -George Santayana ",
            "'If at first you don't succeed, skydiving is not for you.' -Steven Wright",
            "'The universe has a twisted sense of humor.'<br>– Paraphrased from *The Dresden Files*",
            "THE END IS NEAR!<br>No seriously, watch your step.",
            "Doooom! Doom I say, DOOM!",
            "What fortune?",
            "What cookies?",
            "ICY GOLF BALLS OF DEATH FALLING FROM THE SKY!",
            "'OH THE HUMANITY!'",
            `Cave Johnson: When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! "I don't want your damn lemons!" Demand to see life's manager! I'm gonna get my engineers to invent a combustible lemon that'll burn your house down!<br>GLaDOS: Burning people. He says what we're all thinking.<br>– *Portal 2*`,
            "'Duct tape is like the force. It has a light side, a dark side, and it holds the universe together....' -Carl Zwanzig",
            "'Opportunity is missed by most people because it is dressed in overalls and looks like work.' -Thomas A. Edison",
            "'Always acknowledge a fault. This will throw those in authority off their guard and give you an opportunity to commit more.'-Mark Twain",
            "'The problem with political jokes is they get elected.'-Henry Cate VII",
            "'Dreaming permits each and every one of us to be quietly and safely insane every night of our lives.'-William Dement",
            "'I will love the light for it shows me the way, yet I will endure the darkness for it shows me the stars.'-Og Mandino",
            "'A fashion is nothing but an induced epidemic.'-George Bernard Shaw",
            "'He who fights too long against dragons becomes a dragon himself; and if you gaze too long into the abyss, the abyss will gaze into you.' -Friedrich Nietzsche",
            "'Seeing, contrary to popular wisdom, isn't believing. It's where belief stops, because it isn't needed any more.' -Terry Pratchett",
            "'The road to truth is long, and lined the entire way with annoying bastards.' -Alexander Jablokov",
            "'It's not that I'm afraid to die, I just don't want to be there when it happens.'-Woody Allen",
            "HELP! HELP! IM BEING OPRESSED!",
            "'If being sane is being normal, I'd rather be completely mental.'-Angelina Jolie",
            "'There is a theory which states that if ever anybody discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable. There is another theory which states that this has already happened.' -Douglas Adams",
            "'He who binds himself to joy <br> Doth the winged life destroy; <br> But he who kisses the joy as it flies <br> Lives in Eternity's sunrise.' -William Blake",
            "'The man who has nothing to boast of but his illustrious ancestry is like the potato - the best part under ground.' -Thomas Overbury",
            "'Fear less, hope more; <br>  Whine less, breathe more; <br> Talk less, say more; <br> Hate less, love more; <br>  And all good things are yours.'-Swedish Proverb",
            "'Sanity calms, but madness is more interesting.' -John Russell",
            "'If everything in life had a point, there would be no place to sit,' -Blaise Pascal",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
            "insert message here",
          ];
